### ISSUE TITLE
Android studio error : PriorityScheduler(int) has private access in me. ronshapiro.rx.priority.PriorityScheduler

### ISSUE THREAD

**Issue by j2emanue** [ronshapiro/rxjava-priority-scheduler#5]
as soon as i drop your example into my android project in android studio it says PriorityScheduler(int) has private access in me. ronshapiro.rx.priority.PriorityScheduler   How can this be fixed ? Here is the code im running, simply a copy and almost paste of your example:    

final int PRIORITY_HIGH = 10;
        final int PRIORITY_LOW = 1;

```
    PriorityScheduler scheduler = new PriorityScheduler();//fails here
    Observable.just(1, 2, 3, 4, 5)
            .subscribeOn(scheduler.priority(PRIORITY_LOW));
    // .subscribe(System.out::println);

    Observable.just(6, 7, 8, 9, 10)
            .subscribeOn(scheduler.priority(PRIORITY_HIGH));
    // .subscribe(System.out::println);
```

**Comment by ronshapiro** [comment]
Check out `PriorityScheduler.create()` and `PriorityScheduler.withConcurrency(int)` instead
